"""add idempotency key to requests

Revision ID: b0b98abae0cf
Revises: 998fc0000cd0
Create Date: 2026-08-19 18:43:51.526479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0b98abae0cf'
down_revision: Union[str, Sequence[str], None] = '998fc0000cd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('idempotency_key', sa.String(length=64), nullable=True))
    op.create_unique_constraint(op.f('uq_requests_idempotency_key'), 'requests', ['idempotency_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_requests_idempotency_key'), 'requests', type_='unique')
    op.drop_column('requests', 'idempotency_key')
    # ### end Alembic commands ###
